### ISSUE TITLE
Class 'Container' not found

### ISSUE THREAD

**Issue by stoopkid1** [romanpitak/dotMailer-API-v2-PHP-client#24]
Following your Single example....i've installed via Composer (first time using Composer), but am encountering a Fatal error:

Where did I go wrong?

`PHP Fatal error:  Class 'Container' not found in /Applications/MAMP/htdocs/dotmailer/index.php on line 5`

<img width="217" alt="screenshot 2016-05-11 11 40 01" src="https://cloud.githubusercontent.com/assets/2205744/15188791/2e3011d8-176d-11e6-86a0-3873504e1442.png">
<img width="583" alt="screenshot 2016-05-11 11 40 16" src="https://cloud.githubusercontent.com/assets/2205744/15188792/307101a0-176d-11e6-8bc4-1c1b5ba0566d.png">

**Comment by romanpitak** [comment]
Hi @stoopkid1, you must use the correct `namaspace`

```php
<?php
namespace DotMailer\Api;

$resources = Container::newResources($credentials);
```

or instantiate with the full class name

```php
<?php
$resources = \DotMailer\Api\Container::newResources($credentials);
```

**Comment by printmypic** [comment]
I had the same issue it is not a big deal to add 
namespace DotMailer\Api;

to your first example...

**Comment by sami616** [comment]
With this in mind, how would i catch this exception for example?

`namespace DotMailer\Api\DataTypes;

$contact = new ApiContact();
$contact->email = $_POST['email'];
$contact->emailtype = $_POST['email_type'];


try {
	$contact = $resources->PostContacts('invalid input');
} catch (Exception $e) {
	echo $e->getMessage();
}`
