### ISSUE TITLE
PostContactsTransactionalDataImport method is incomplete

### ISSUE THREAD

**Issue by ishakuta** [romanpitak/dotMailer-API-v2-PHP-client#7]
Hi,

this method
https://github.com/romanpitak/dotMailer-API-v2-PHP-client/blob/master/src/Resources/Resources.php#L492
doesn't use passed parameter, so it's always returns an error that transactional data can not be null.

**Comment by romanpitak** [comment]
Fixed in romanpitak/dotMailer-API-v2-PHP-client@0e45fc71306cb017bbe0dcd972549cd95201ef96
