### ISSUE TITLE
ApiTransactionalDataImportStatuses has incorrect constants

### ISSUE THREAD

**Issue by ishakuta** [romanpitak/dotMailer-API-v2-PHP-client#8]
ApiTransactionalDataImportStatuses has incorrect constants

    const NOT_STARTED = 'NotStarted';
    const NOT_FINISHED = 'NotStarted';
    const FINISHED = 'NotStarted';
    const FAILED = 'NotStarted';

**Comment by romanpitak** [comment]
Fixed in romanpitak/dotMailer-API-v2-PHP-client@0e45fc71306cb017bbe0dcd972549cd95201ef96
